# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 038f57cfa0796f10ec0dd5df35e34c0955b2b5db237c9f28fdfde3e0fd741ada952f7a10b9444b3ca5ad7b7e25fa25ec6e9767a57d1f01852fa9c126e80f2aa4

test:
  secret_key_base: ef9e2291660d647662f6e24b48d58fe439d1b62e87e297666bf9e9b4eda830e254e1a6cda5327ffa897225b08c1834f57da63fd36cee9278a036098734aa43e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
